#!/bin/bash

logger --tag panjerdDiskMount "Kreeg het verzoek om \"$1\" te koppelen."

if [[ "${1}" -eq "PANJERD-3" ]]; then
	logger --tag panjerdDiskMount 'We gaan pogen de disk te kopplen'
	(LC_ALL=C mount -o ro "/dev/disk/by-label/${1}" /media/panjerddata &)&
else
	logger --tag panjerdDiskMount 'Dat doen we dus mooi even niet'
fi



